- name: Configuring backend server
  hosts: backend
  become: yes
  tasks:
  - name: Disable current nodejs
    ansible.buitin.command: dnf module disable nodejs -y

  - name:  Enable nodejs 20
    ansible.buitin.command: dnf module enable nodejs:20 -y
  - name: Install nodejs 
    ansible.builtin.package:
      name: nodejs
      state: present 
  - name: Create expense user
    ansible.builtin.user:
      name: expense
  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory


